[package]

name = "irc"
version = "0.0.1"
authors = ["Leif Walsh <leif.walsh@gmail.com>"]

[dependencies]
env_logger = "0.3"
getopts = "0.2"
log = "0.3"
postgres = "0.8"
postgres_macros = "0.1"
rand = "0.3"
regex = "0.1"
regex_macros = "0.1"

[[bin]]
name = "hiphopabotamus"
test = false